### ISSUE TITLE
Frequently seeing RuntimeError: event loop is closed with connaisseur pods 

### ISSUE THREAD

**Issue by dbbhat** [sse-secure-systems/connaisseur#1205]
**Describe the bug**

We are frequently seeing occurrences of `RuntimeError: event loop is closed` across all our K8S clusters with long running connaisseur pods 

```
NAME                                      READY   STATUS    RESTARTS   AGE
connaisseur-deployment-58dcdfc7ff-8fxqm   1/1     Running   0          2d5h
connaisseur-deployment-58dcdfc7ff-fn298   1/1     Running   0          2d5h
connaisseur-deployment-58dcdfc7ff-qbcss   1/1     Running   0          2d5h
```

```
{"timestamp": "2023-08-25 01:41:54.716856", "message": "automatic approval for unchanged image \"<registry>:<tag>@sha256:<digest>\".", "admission_review": {"user": "system:serviceaccount:<foo>", "operation": "UPDATE", "kind": "Pod", "name": "<foo-pod>", "namespace": "<foo-ns>"}, "image": "<registry>:<tag>@sha256:<digest>"}
{"timestamp": "2023-08-25 01:41:54.763673", "client_ip": "100.64.0.14", "method": "POST", "path": "/mutate", "query": "timeout=30s", "protocol": "HTTP/1.1", "status_code": "200"}
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f4c2cfde3e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 765, in close
    self.write_eof()
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 751, in write_eof
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{"timestamp": "2023-08-25 01:41:54.922689", "message": "automatic approval for unchanged image \"<registry>:<tag>@sha256:<digest>\".", "admission_review": {"user": "system:serviceaccount:<foo>", "operation": "UPDATE", "kind": "Pod", "name": "<foo-pod>", "namespace": "<foo-ns>"}, "image": "<registry>:<tag>@sha256:<digest>"}
```
The error seems to eventually recover, but frequent occurrences of this error is concerning. 

**Expected behavior**
Connaisseur should not run into these asyncio errors 

**Optional: Versions (please complete the following information as relevant):**

 - Kubernetes Cluster: v1.23
 - Connaisseur: v3.0.0

**Comment by phbelitz** [comment]
Sorry, i have been on vacation this week. I'll have a look next week.

**Comment by jacobkoren1** [comment]
I also saw it and it was fixed using:
```
    result = loop.run_until_complete(__async_mutate());
    return result;
```
With the event loop initialized outside the function.
