### ISSUE TITLE
Connaisseur didn't worked post following the README document

### ISSUE THREAD

**Issue by indresh28** [sse-secure-systems/connaisseur#447]
Hi,
Am using Ubuntu 0.04 LTS (Focal Fossa) VM, which has k3s environment.
Version details:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15+k3s2", GitCommit:"0fbbc5af7c17003cc9259b741f6d672ae93d0cd0", GitTreeState:"clean", BuildDate:"2021-10-05T18:58:35Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

Connaisseur failed to admit the pod as it didn't get the result in specified time.

When I try to deploy the pod using:
```
kubectl run hello-world --image=docker.io/hello-world
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run -- 
generator=run-pod/v1 or kubectl create instead.
Error from server (InternalError): Internal error occurred: failed calling webhook "connaisseur-svc.connaisseur.svc": Post 
"https://connaisseur-svc.connaisseur.svc:443/mutate?timeout=30s": context deadline exceeded (Client.Timeout exceeded while 
awaiting headers)
```

**Connaisseur Pod logs:**
    After posting the pod creation request took around 5 min to arrive below logs.
```
[2021-12-09 08:22:07,950] ERROR: Traceback (most recent call last):
  File "/app/connaisseur/flask_application.py", line 52, in mutate
    response = asyncio.run(__admit(admission_request))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/app/connaisseur/flask_application.py", line 109, in __admit
    await patches
  File "/app/connaisseur/flask_application.py", line 156, in __validate_image
    trusted_digest = await validator.validate(image, **policy_rule.arguments)
  File "/app/connaisseur/validators/notaryv1/notaryv1_validator.py", line 44, in validate
    signed_image_targets = await self.__process_chain_of_trust(
  File "/app/connaisseur/validators/notaryv1/notaryv1_validator.py", line 114, in __process_chain_of_trust
    trust_data_list = await asyncio.gather(
  File "/app/connaisseur/validators/notaryv1/notary.py", line 110, in get_trust_data
    async with session.get(**request_kwargs) as response:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 448, in _request
    with timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

[2021-12-09 08:22:07,952] INFO: 10.42.0.1 - - [09/Dec/2021 08:22:07] "POST /mutate?timeout=30s HTTP/1.1" 200 -
socket.error 8
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cheroot/server.py", line 1287, in communicate
    req.respond()
  File "/usr/local/lib/python3.10/site-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.10/site-packages/cheroot/wsgi.py", line 145, in respond
    self.write(chunk)
  File "/usr/local/lib/python3.10/site-packages/cheroot/wsgi.py", line 231, in write
    self.req.write(chunk)
  File "/usr/local/lib/python3.10/site-packages/cheroot/server.py", line 1133, in write
    self.conn.wfile.write(chunk)
  File "/usr/local/lib/python3.10/site-packages/cheroot/makefile.py", line 438, in write
    res = super().write(val, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cheroot/makefile.py", line 36, in write
    self._flush_unlocked()
  File "/usr/local/lib/python3.10/site-packages/cheroot/makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/local/lib/python3.10/socket.py", line 723, in write
    return self._sock.send(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1205, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2384)

```

Can you help me to figure out what is going on?.

**Comment by xopham** [comment]
@indresh28 you are following the simple [README](https://github.com/sse-secure-systems/connaisseur), right?
Did you adapt the `helm/values.yaml` in any way or do you use the out-of-the-box configuration?
The installation happened without problems and `kubectl get all -n connaisseur` shows all pods are up and running?

It appears that Connaisseur is not able to reach the internet. Is it possible that your cluster denies egress traffic or the DNS (e.g. coredns) is not working? You might check the kube-system namespace whether those pods are up and running.

It is however unfortunate that we use the [aiohttp timeout](https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts) here that far exceeds the Admission timeout of 30s which should be adjusted. I raised #448 .

Let me know if that helps :slightly_smiling_face:

**Comment by indresh28** [comment]
@xopham thanks for responding rest of the pods looks fine in the cluster. Which ports should be open for egress traffic?

**Comment by xopham** [comment]
@indresh28 was just wondering about connectivity in general, as it seems that aiohttp cannot reach notary.docker.io

**Comment by xopham** [comment]
@indresh28 I also gave k3s a quick shot on my ubuntu 21.10 and that worked like a charm. However, I was using k3s based on k8s v1.21 and encountered some cgroup issues using v1.19 as in your case. Any chance, you could check whether the problem persists for v1.21?

**Comment by indresh28** [comment]
@xopham I tried on 1.21 too on same setup, might the environment has some restrictions. So tried on the different machine it worked. Thanks for your inputs, closing the issue.
