### ISSUE TITLE
CRDs cause errors (both for RBAC and SUPPORTED_API_VERSIONS)

### ISSUE THREAD

**Issue by funkypenguin** [sse-secure-systems/connaisseur#582]
**Describe the bug**
<A clear and concise description of what the bug is.>

The connaisseur webhook seems to intercept _any_ CREATE/UPDATE operations, even those to CRDs. However, the clusterolebinding doesn't have access to "get" these resources, and this creates errors like this: 

```
[2022-03-17 04:47:13,564] ERROR: Traceback (most recent call last):
  File "/app/connaisseur/flask_application.py", line 71, in mutate
    response = asyncio.run(__admit(admission_request))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/app/connaisseur/flask_application.py", line 139, in __admit
    await patches
  File "/app/connaisseur/flask_application.py", line 165, in __validate_image
    image in admission_request.wl_object.parent_containers.values()
  File "/app/connaisseur/workload_object.py", line 68, in parent_containers
    parent = k_api.request_kube_api(
  File "/app/connaisseur/kube_api.py", line 22, in request_kube_api
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.96.0.1:443/apis/vault.banzaicloud.com/v1alpha1/namespaces/preview-notifications-pr-7/vaults/vault
```

**Expected behavior**

Since we already have a [preset list](https://github.com/sse-secure-systems/connaisseur/blob/master/helm/templates/role.yaml#L10) of objects we allow connaisseur to watch, connaisseur should only respond to these objects, not all objects.

**Optional: To reproduce**

* Deploy connaisseur
* Add any service which uses CRDs to specify images (the above example uses [banzaicloud's bank-vaults](https://github.com/banzaicloud/bank-vaults/blob/main/operator/deploy/crd.yaml))
* Watch connaisseur logs
* Deploy a CR for the service, and observe the error

**Optional: Versions (please complete the following information as relevant):**
 - Connaisseur: 2.5.1

**Optional: Additional context**

As a test, I manually edited the clusterrole to permit `get` to all the CRDs we use. In the example below, minio-operator's Tenant CR was used. Although connaisseur was able to `get` the object, it still produced an error:

```
[2022-03-17 01:57:30,798] ERROR: Traceback (most recent call last):
  File "/app/connaisseur/flask_application.py", line 71, in mutate
    response = asyncio.run(__admit(admission_request))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/app/connaisseur/flask_application.py", line 139, in __admit
    await patches
  File "/app/connaisseur/flask_application.py", line 165, in __validate_image
    image in admission_request.wl_object.parent_containers.values()
  File "/app/connaisseur/workload_object.py", line 81, in parent_containers
    parent_containers.update(WorkloadObject(parent, self.namespace).containers)
  File "/app/connaisseur/workload_object.py", line 40, in __init__
    if self.api_version not in SUPPORTED_API_VERSIONS[self.kind]:
KeyError: 'Tenant'
```

**Comment by funkypenguin** [comment]
Thanks @xopham, but I'm afraid automatic child approval doesn't prevent the errors.. this one is with automatic child approval enabled:

```

[2022-03-18 09:50:33,607] ERROR: Traceback (most recent call last):
  File "/app/connaisseur/flask_application.py", line 71, in mutate
    response = asyncio.run(__admit(admission_request))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/app/connaisseur/flask_application.py", line 139, in __admit
    await patches
  File "/app/connaisseur/flask_application.py", line 165, in __validate_image
    image in admission_request.wl_object.parent_containers.values()
  File "/app/connaisseur/workload_object.py", line 68, in parent_containers
    parent = k_api.request_kube_api(
  File "/app/connaisseur/kube_api.py", line 22, in request_kube_api
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.96.0.1:443/apis/vault.banzaicloud.com/v1alpha1/namespaces/preview-gatewayfe-pr-153/vaults/vault
```

**Comment by xopham** [comment]
Thanks for sharing @funkypenguin . think we should improve both, automatic child approval and handling of CRDs.
@hsuchan has mentioned a similar problem.
As I see it, we can:
* ignore the CRDs and only validate the resulting resources, e.g. pods (sort of how automatic child approval should work)
* attempt to validate images in CRDs by guessing the definition

In case, CRDs are not mutated that can in some cases cause issues when a tool is deployed that confirms that resources are deployed as per the configurations.

**Comment by funkypenguin** [comment]
From my perspective, mutating only the pods is safest. I can imagine all kinds of unpleasant consequences to guessing at CRDs, and blindly changing "image" fields!

This may be better placed into a separate issue, but one complication of the mutation is the obscuring of the original image tag. Could we add an annotation to mutated pods to indicate what the original tag was? Ideally the deployment would then be un-mutated, but the pods themselves would be. (This is how Istio's sidecar is done). Speaking of Istio, another handy feature is the ability to ignore mutation on a pod-by-pod basis, if a particular annotation is found. I can see this being a helpful option in Connaisseur too, for odd things like busybox-based initContainers, etc.. :)

**Comment by xopham** [comment]
@funkypenguin going back to the original error: you mentioned banzai cloud's bank vault. Would you have a minimal example how to configure Connaisseur and how to deploy the vault to get the error?

**Comment by funkypenguin** [comment]
Hi @xopham,

Sure, here's a really minimal reproduction, tested using KinD:

1. Deploy vault-operator:

```
helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
helm upgrade --install vault-operator banzaicloud-stable/vault-operator
```

2. Deploy connaisseur:

```
helm repo add connaisseur https://sse-secure-systems.github.io/connaisseur/charts
helm upgrade --install connaisseur connaisseur/connaisseur
```

3. Deploy one of the bank-vaults sample CRs:

```
kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/main/operator/deploy/cr-priority.yaml
```

4. Observe the connaisseur logs:

```
 kubectl logs -l app.kubernetes.io/name=connaisseur
```

Output is something like this:

```
[2022-03-23 08:09:05,384] INFO: 10.244.0.1 - - [23/Mar/2022 08:09:05] "POST /mutate?timeout=30s HTTP/1.1" 200 -
    image in admission_request.wl_object.parent_containers.values()
  File "/app/connaisseur/workload_object.py", line 68, in parent_containers
    parent = k_api.request_kube_api(
  File "/app/connaisseur/kube_api.py", line 22, in request_kube_api
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.96.0.1:443/apis/vault.banzaicloud.com/v1alpha1/namespaces/default/vaults/vault

[2022-03-23 08:07:26,766] INFO: 10.244.0.1 - - [23/Mar/2022 08:07:26] "POST /mutate?timeout=30s HTTP/1.1" 200 -
```

**Comment by xopham** [comment]
@funkypenguin thanks for sharing. That was super helpful.
Here, are a few notes:
* with automaticChildApproval (ACA) on, I was able to fix this. please test with `docker.io/xoph/connaisseur:v2.5.2-rc2` connaisseur image (private repo, not signed)
* I could not reproduce an error with ACA off, but got a 'serviceaccount missing' error which on first sight seemed unrelated to Connaisseur

Might need some further testing and fine-tuning, but would appreciate if you could see if this resolves your problem :pray:

**Comment by xopham** [comment]
@funkypenguin please test with `xoph/connaisseur:v2.5.2-rc3`, as it contains both #589 and #590 .

If the fixes work, we aim to release shortly :rocket:

**Comment by funkypenguin** [comment]
Thanks heaps, @xopham, `-rc3` seems to work as expected :)
